apiVersion: v2
name: backend-api
description: Backend Flask API Helm chart
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - backend
  - api
  - flask
  - python
home: https://github.com/your-org/infra-kata
sources:
  - https://github.com/your-org/infra-kata
maintainers:
  - name: DevOps Team
    email: devops@yourorg.com
