apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=__ECR_REGISTRY__/backend-api:latest
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  labels:
    app.kubernetes.io/name: backend-api
    app.kubernetes.io/part-of: infra-kata
spec:
  project: default
  source:
    repoURL: __GIT_REPO_URL__
    targetRevision: __GIT_TARGET_REVISION__
    path: k8s/charts/backend
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: __ECR_REGISTRY__/backend-api
        - name: image.tag
          value: latest
        - name: image.pullPolicy
          value: Always
        - name: imagePullSecrets[0].name
          value: ecr-secret
        - name: ingress.enabled
          value: "true"
        - name: ingress.className
          value: nginx
        - name: ingress.hosts[0].host
          value: api.local
        - name: ingress.hosts[0].paths[0].path
          value: /
        - name: ingress.hosts[0].paths[0].pathType
          value: Prefix
        - name: service.type
          value: ClusterIP
        - name: service.port
          value: "80"
        - name: resources.requests.cpu
          value: 100m
        - name: resources.requests.memory
          value: 128Mi
        - name: resources.limits.cpu
          value: 500m
        - name: resources.limits.memory
          value: 512Mi
        - name: autoscaling.enabled
          value: "true"
        - name: autoscaling.minReplicas
          value: "2"
        - name: autoscaling.maxReplicas
          value: "10"
        - name: autoscaling.targetCPUUtilizationPercentage
          value: "80"
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
